# permissions for end users to edit awesomejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awesomejob-editor-role
rules:
- apiGroups:
  - apps.tutorial.io
  resources:
  - awesomejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.tutorial.io
  resources:
  - awesomejobs/status
  verbs:
  - get
