# permissions for end users to edit nicejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nicejob-editor-role
rules:
- apiGroups:
  - batch.tutorial.io
  resources:
  - nicejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.io
  resources:
  - nicejobs/status
  verbs:
  - get
