# permissions for end users to view nicejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nicejob-viewer-role
rules:
- apiGroups:
  - batch.tutorial.io
  resources:
  - nicejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.tutorial.io
  resources:
  - nicejobs/status
  verbs:
  - get
